############################################################
#
# 搜索微服务
# web访问端口号  约定：8006
#
############################################################
server:
  port: 8006
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: service-search
  data:
    elasticsearch:
      cluster-name: imooc-elasticsearch
      cluster-nodes: 127.0.0.1:9300